feat: send pageview to google analytics 4 when clicking action
EyeSeeTea/home-page-app-dev pull request #27
Opened 2024-02-12 01:26 UTC by p3rcypj

### :pushpin: References

-   **Issue:** Closes #?

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

### :fire: Testing

2024-04-23 07:42 UTC, anagperal requested changes
thanks @p3rcypj ! Just some comments:

- Instead of using directly compositionRoot.analytics.sendPageView in HomePage and in AdditionalComponents, create an useAnalystics hook to encapsulate this so it can be used throughout the app
- Also in https://github.com/EyeSeeTea/uhcpw we use https://www.npmjs.com/package/react-ga4. Maybe for the future is easier to config and use?

2024-04-23 07:43 UTC, anagperal commented on src/webapp/pages/settings/useConfig.ts
> +            compositionRoot.config.updateGoogleAnalyticsCode(code);
Add await here, if not in SettingsPage component, when you are saving the G4 code, the page reloads without waiting to save the code, so never is saved

2024-04-26 09:04 UTC, MiquelAdell reviewed
Finally got to test this.
I identified some functionality that may be missing or not needed.
I can confirm that views are tracked correctly if "the destination page" is inside home page app. If it is outside of it (it goes somewhere else) it's not tracked.

I don't know if we need to track those links.

If we need to track those links we could capture the click, send the event, and then resume the click

I recorded a video but I think it may not be needed if the text explanation is clear enough:

https://github.com/EyeSeeTea/home-page-app-dev/assets/4996457/c8879d58-3985-4f27-aec5-87bd8674ac62

2024-04-26 13:12 UTC, p3rcypj commented
Just a comment for @MiquelAdell and @anagperal, events on real-time may take 20 seconds or even 1 minute to show in the report (yes "real-time", google should add small info about this)

2024-04-26 13:47 UTC, anagperal approved these changes
thanks @p3rcypj ! I've checked [commit](https://github.com/EyeSeeTea/home-page-app-dev/pull/27/commits/fdfd91b2ee3a6212ceb6c15b91d9217e1e3d99f7) and [commit](https://github.com/EyeSeeTea/home-page-app-dev/pull/27/commits/e6a472a65a773dbc59d7aa6fa509227637ffcc1a)  and code it's ok

2024-04-26 13:48 UTC, merged