Feat/internal page
EyeSeeTea/home-page-app-dev pull request #29
Opened 2024-02-22 16:06 UTC by p3rcypj

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8693u555f

### :memo: Implementation

- Added flag "Execute on init" to landing pages
- Added action type "Landing page" to be able to go to another landing page

- Validations on update and import:
  - Action with type "Landing page" cannot be created if the landing page id doesn't exist
  - Action with type "Landing page" cannot be added to landing page that references itself on action

### :video_camera: Screenshots/Screen capture

![image](https://github.com/EyeSeeTea/home-page-app-dev/assets/43061485/8a1ba5f5-2357-4afc-baf3-dec6b6a4004f)
![image](https://github.com/EyeSeeTea/home-page-app-dev/assets/43061485/9791977b-bda6-420e-847c-769be54b4e09)
![image](https://github.com/EyeSeeTea/home-page-app-dev/assets/43061485/f6bd0fab-d371-4cc9-9f16-3b7c0377b3ad)

2024-03-21 15:00 UTC, p3rcypj commented on src/data/entities/Config.ts
Clean Arch

2024-03-21 15:00 UTC, p3rcypj commented on src/data/entities/Instance.ts
Clean Arch

2024-03-21 15:00 UTC, p3rcypj commented on src/data/entities/JSONAction.ts
Feature

2024-03-21 15:01 UTC, p3rcypj commented on src/data/entities/PersistedLandingNode.ts
Clean Arch

2024-03-21 15:01 UTC, p3rcypj commented on src/data/entities/PersistedSettings.ts
Clean Arch

2024-03-21 15:02 UTC, p3rcypj commented on src/data/repositories/ActionDefaultRepository.ts
> +            launchPageId: model.launchPageId,
Feature

2024-03-21 15:03 UTC, p3rcypj commented on src/data/repositories/ActionDefaultRepository.ts
Clean Arch but one line of Feature L153

2024-03-21 16:14 UTC, p3rcypj commented on src/data/repositories/Dhis2ConfigRepository.ts
Clean Arch

2024-03-21 16:14 UTC, p3rcypj commented on src/data/repositories/InstanceDhisRepository.ts
Clean Arch

2024-03-21 16:15 UTC, p3rcypj commented on src/data/repositories/LandingNodeDefaultRepository.ts
> +            executeOnInit: true,
Feature

2024-03-21 16:15 UTC, p3rcypj commented on src/domain/entities/LandingNode.ts
Feature

2024-03-21 16:15 UTC, p3rcypj commented on src/domain/repositories/ActionRepository.ts
Clean Arch

2024-03-21 16:17 UTC, p3rcypj commented on src/data/repositories/LandingNodeDefaultRepository.ts
Clean Arch but one line L70 Feature

2024-03-21 16:18 UTC, p3rcypj commented on src/data/utils/d2-api.ts
Clean Arch

2024-03-21 16:18 UTC, p3rcypj commented on src/domain/entities/Action.ts
Feature

2024-03-21 16:18 UTC, p3rcypj commented on src/domain/repositories/ConfigRepository.ts
Clean Arch

2024-03-21 16:19 UTC, p3rcypj commented on src/domain/repositories/InstanceRepository.ts
Clean Arch

2024-03-21 16:19 UTC, p3rcypj commented on src/domain/repositories/LandingNodeRepository.ts
Clean Arch

2024-03-21 16:19 UTC, p3rcypj commented on src/domain/usecases/CreateLandingNodeUseCase.ts
Clean Arch

2024-03-21 16:19 UTC, p3rcypj commented on src/domain/usecases/DeleteLandingNodesUseCase.ts
Clean Arch

2024-03-21 16:20 UTC, p3rcypj commented on src/webapp/pages/home/HomePage.tsx
Feature

2024-03-21 16:20 UTC, p3rcypj commented on src/webapp/pages/App.tsx
Clean Arch

2024-03-21 16:20 UTC, p3rcypj commented on src/webapp/contexts/app-context.tsx
Clean Arch

2024-03-21 16:20 UTC, p3rcypj commented on src/webapp/components/landing-page-list-table/LandingPageListTable.tsx
Feature

2024-03-21 16:20 UTC, p3rcypj commented on src/webapp/components/landing-page-edit-dialog/LandingPageEditDialog.tsx
Feature

2024-03-21 16:21 UTC, p3rcypj commented on src/webapp/components/item-sub-section/ItemSubSection.tsx
Feature

2024-03-21 16:21 UTC, p3rcypj commented on src/webapp/components/item-section/ItemSection.tsx
Feature

2024-03-21 16:21 UTC, p3rcypj commented on src/webapp/components/item-root/ItemRoot.tsx
Feature

2024-03-21 16:21 UTC, p3rcypj commented on src/webapp/components/item-category/ItemCategory.tsx
Feature

2024-03-21 16:21 UTC, p3rcypj commented on src/webapp/components/additional-components/AdditionalComponents.tsx
Feature

2024-03-21 16:22 UTC, p3rcypj commented on src/webapp/components/action-list-table/ActionListTable.tsx
Feature

2024-03-21 16:22 UTC, p3rcypj commented on src/webapp/components/action-creation-wizard/steps/index.ts
Feature

2024-03-21 16:22 UTC, p3rcypj commented on src/webapp/components/action-creation-wizard/steps/GeneralInfoStep.tsx
Feature

2024-03-21 16:22 UTC, p3rcypj commented on src/webapp/components/action-creation-wizard/ActionCreationWizard.tsx
Feature

2024-03-21 16:22 UTC, p3rcypj commented on src/webapp/CompositionRoot.ts
Clean Arch

2024-03-21 16:22 UTC, p3rcypj commented on src/domain/usecases/common.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/UpdateLandingNodeUseCase.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/UpdateActionUseCase.ts
Feature

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/SwapLandingChildOrderUseCase.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/ListLandingChildrenUseCase.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/ListActionsUseCase.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/ImportLandingNodesUseCase.ts
Clean Arch

2024-03-21 16:23 UTC, p3rcypj commented on src/domain/usecases/ImportLandingNodesTranslationsUseCase.ts
Clean Arch

2024-03-21 16:24 UTC, p3rcypj commented on src/domain/usecases/ImportActionsUseCase.ts
Both Clean Arch and Feature

2024-03-21 16:24 UTC, p3rcypj commented on src/domain/usecases/GetConfigUseCase.ts
Clean Arch

2024-03-21 16:24 UTC, p3rcypj commented on src/domain/usecases/ExportLandingNodesUseCase.ts
Clean Arch

2024-03-21 16:24 UTC, p3rcypj commented on src/domain/usecases/ExportLandingNodesTranslationsUseCase.ts
Clean Arch

2024-03-21 16:25 UTC, p3rcypj commented on src/domain/usecases/ExportActionsUseCase.ts
Clean Arch

2024-03-22 07:14 UTC, xurxodev requested changes
Thanks @p3rcypj 

Maybe it's my little knowledge about this project because my last time was a long time ago, but I tested quickly the functionality previous to review it from technical point of view, and it doesn't work.

My test:
url: https://dev.eyeseetea.com/play

- I edit the first action to landing type and select the unique landing page (main) to launch.
- When I click in the action from the home appear a snackbar with the text 'Page not found'

2024-03-27 04:48 UTC, p3rcypj commented
@xurxodev Kinda strange, it should say at least as error "You are already in this page". The only thing that comes to my mind is possible the main landing page changing IDs as is the default¿¿ I tried also in [dev.eyeseetea.com/play](dev.eyeseetea.com/play) and yes it throws error but the mentioned before that should be intended.

The general steps to reproduce the usecase for this feature should be something like: Create new landing with execute on init disabled, put some content or actions on that landing, create a new one action of landing type and select the previous landing, and add that action to the landing that it executes on init.

2024-04-02 08:57 UTC, xurxodev approved these changes
Thanks @p3rcypj 

I've tested the use case that you indicate and works. However, the use case that I indicate fail appearing the page not found message.

Anyway, I leave the functional review to @adrianq 

I've reviewed the PR from an architecture point of view, and I've found some issues about architecture to review. I'm going to approve the PR because it is big, and it has mixed new functionality and architecture refactors. 

Furthermore, I've written the issues to review in the pair programming coding dojo in the task 
https://app.clickup.com/t/86943v5z0

2024-04-08 16:05 UTC, adrianq commented
@xurxodev I reviewed the issue this morning with @p3rcypj He has clearly identified where the problem is coming from. It is true this is not the most typical use case but we should be able to handle this problem in a more elegant way. For now, @p3rcypj can focus on the reactors he has discussed with you and create a different PR to fix this issue afterwards

2024-04-26 08:25 UTC, merged