Feature/new icons
EyeSeeTea/home-page-app-dev pull request #7
Opened 2023-01-20 15:29 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/865bhqywt

### :memo: Implementation

### :art: Screenshots

### :fire: Testing

2023-01-23 13:39 UTC, adrianq requested changes
@deeonwuli Just one comment below. Btw, why are the branch and the PR name as new-icons? This has nothing to do with icons, right?

2023-01-23 13:39 UTC, adrianq commented on package.json
>      "name": "dhis2-home-page",
Why are you keeping "dhis2" in the name of the app? The zip file generated during the build process is named "dhis2-home-page" which may be confusing for the user

2023-01-24 08:18 UTC, deeonwuli commented
> @deeonwuli Just one comment below. Btw, why are the branch and the PR name as new-icons? This has nothing to do with icons, right?

that was a mistake on my part. i've renamed the PR now though.

2023-01-25 08:25 UTC, tokland approved these changes

2023-01-25 08:25 UTC, tokland commented on src/webapp/pages/about/AboutPage.tsx
> -        i18n.t("DHIS2 Home page App is a DHIS2 application that aims to provide direct links to Dhis2 applications."),
[very minor] `DHIS2`, then `Dhis2`.

2023-01-25 08:34 UTC, merged